// Generated by https://quicktype.io

export interface IResetPasswordResponse {
  status: string;
  token: string;
  data: Data;
}

export interface Data {
  user: User;
}

export interface User {
  role: string;
  _id: string;
  name: string;
  faculty: string;
  year: number;
  department: string;
  email: string;
  __v: number;
}

// Generated by https://quicktype.io

export interface IResetPasswordError {
  status: string;
  error: Error;
  message: string;
  stack: string;
}

export interface Error {
  statusCode: number;
  status: string;
  isOperational: boolean;
}
