// Generated by https://quicktype.io

export interface IChangePasswordResponse {
  status: string;
  error: Error;
  message: string;
  stack: string;
}

export interface Error {
  statusCode: number;
  status: string;
  isOperational: boolean;
}

// Generated by https://quicktype.io

export interface IChangePasswordResponseError {
  status: string;
  error: Error;
  message: string;
  stack: string;
}

export interface Error {
  statusCode: number;
  status: string;
  isOperational: boolean;
}
