// Generated by https://quicktype.io

export interface ISummary {
  status: string;
  data: Data;
}

export interface Data {
  reports: Report[];
}

export interface Report {
  _id: ID;
  numberOfAbsences: number;
  akceptovanych: number;
  zamietnutych: number;
}

export interface ID {
  course: string;
  courseType: string;
  user: User[];
}

export interface User {
  name: string;
  department: string;
  email: string;
  __v: number;
}
